import type { Metadata } from "next";
import "./globals.css";
import "quill/dist/quill.core.css";
import { Providers } from "./providers";
import NavBar  from '../components/Navbar'
import { Prompt } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css";
const Promptfont = Prompt({
  weight: "200",
  style: ["normal", "italic"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body className={`${Promptfont.className} antialiased`}>
        <Providers>
        <div className="md:w-[81rem] sm:w-[550px] md:ml-[9rem]">   
           <NavBar/>
          </div> 
          
          <div className=" h-full md:mx-[15%] md:w-[81rem] sm:w-[600px]">
            {children} 
          </div>
          <footer className="bg-teal-800 text-white py-8 mt-[3%]">
              <h2 className=" font-bold text-2xl md:left-[14rem] text-[2rem] md:mx-[16%] sm:mx-auto">
                LOGO
              </h2>
              <div className="border-t border-white mt-2 md:mx-auto max-sm:mx-[10%] md:w-[81rem]"></div>
              <div className="grid grid-cols-1 md:grid-cols-4 container mt-[2%] mx-auto gap-2 md:w-[81rem]">
                <div className="md:col-span-1 md:text-left">
                  <h3 className="font-bold mb-2">คอร์สของเรา</h3>
                  <ul className="space-y-2">
                    <li>Data</li>
                    <li>Science</li>
                    <li>Tech</li>
                    <li>Business</li>
                  </ul>
                </div>

                <div className="md:col-span-1 md:text-left">
                  <h3 className="font-bold mb-2">เกี่ยวกับเรา</h3>
                  <ul className="space-y-2">
                    <li >สอบถามเรา</li>
                    <li>ติดต่อสอบถามเพิ่มเติม</li>
                    <li>แจ้งปัญหาเกี่ยวกับระบบ</li>
                    <li>ช่องทางการร้องเรียน</li>
                  </ul>
                </div>
                <div className="md:col-span-1 md:text-left">
                  <h3 className="font-bold mb-2">ความปลอดภัย</h3>
                  <ul className="space-y-2">
                    <li>Privacy Policy</li>
                    <li>Terms and Conditions</li>
                    <li>Data Protection Policy Six</li>
                    <li>Cookie Policy</li>
                  </ul>
                </div>

                <div className="md:col-span-1  md:text-left">
                  <h3 className="font-bold mb-2">
                    Lorem Ipsum is simply dummy text of the printing.
                  </h3>
                  <p className="text-sm mb-4">
                    199 ม.6 ต.สุรศักดิ์ อ.ศรีราชา จ.ชลบุรี 20230
                  </p>
                  <h4 className="font-bold mb-2">ติดต่อเรา</h4>
                  <div className="flex gap-4 ">
                    <a href="#" className="text-white">
                      <i className="fab fa-youtube"></i>
                    </a>
                    <a href="#" className="text-white">
                      <i className="fab fa-facebook"></i>
                    </a>
                    <a href="#" className="text-white">
                      <i className="fab fa-twitter"></i>
                    </a>
                    <a href="#" className="text-white">
                      <i className="fab fa-instagram"></i>
                    </a>
                    <a href="#" className="text-white">
                      <i className="fab fa-linkedin"></i>
                    </a>
                  </div>
                </div>
              </div>

              <div className="border-t border-white mt-8 pt-4 text-sm flex flex-col md:flex-row justify-between md:mx-auto max-sm:mx-[10%] md:w-[81rem]">
                <p>Y.I.M Corporation © 2023. All rights reserved.</p>
                <p>0-3335-4580-4 , 0-3835-2611-6</p>
              </div>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
